renamed local tag -> tag2
... because clang on windows claimed collision with a global 'tag'

2023-01-25T20:41:48.9253681Z D:\a\ut\ut\include\boost/ut.hpp(1948,24): error C2220: the following warning is treated as an error [D:\a\ut\ut\build\example\boost_ut_cli_all_dry_run.vcxproj]
2023-01-25T20:41:48.9255192Z D:\a\ut\ut\include\boost/ut.hpp(1948,24): warning C4459: declaration of 'tag' hides global declaration [D:\a\ut\ut\build\example\boost_ut_attr.vcxproj]

???